-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 15, 2018 at 09:07 AM
-- Server version: 10.1.21-MariaDB
-- PHP Version: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `lasi`
--

-- --------------------------------------------------------

--
-- Table structure for table `post`
--

CREATE TABLE `post` (
  `postid` int(11) NOT NULL,
  `nic` varchar(10) NOT NULL,
  `name` varchar(255) NOT NULL,
  `disaster_type` varchar(5) NOT NULL,
  `other_cat` varchar(4) NOT NULL,
  `title` varchar(400) NOT NULL,
  `image` varchar(400) NOT NULL,
  `body` varchar(4000) NOT NULL,
  `date` date NOT NULL,
  `time` time NOT NULL,
  `location` varchar(255) NOT NULL,
  `District` varchar(20) NOT NULL,
  `lat` double NOT NULL,
  `lng` double NOT NULL,
  `image2` varchar(400) NOT NULL,
  `treath_type` varchar(255) NOT NULL,
  `status` varchar(10) NOT NULL,
  `post_type` varchar(20) NOT NULL,
  `death` int(11) NOT NULL,
  `accsident` int(11) NOT NULL,
  `mising` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `post`
--

INSERT INTO `post` (`postid`, `nic`, `name`, `disaster_type`, `other_cat`, `title`, `image`, `body`, `date`, `time`, `location`, `District`, `lat`, `lng`, `image2`, `treath_type`, `status`, `post_type`, `death`, `accsident`, `mising`) VALUES
(31, '900870902v', 'Dewni Amarakoon', 'rsa', 'none', 'O/L Student dies Under Tragic Circumstances.', 'post_image/2.jpg', 'A student who had sat for GCE O/L examination this year died yesterday (21) when the tractor driven by him skidded off the road and hit a roadside tree.\r\n\r\nThe deceased was Isuru Sampath from Thambuttegama,Anuradhapura.\r\nOur correspondent said Isuru met with this tragic accident when he was driving a tractor with 2 other friends.\r\n', '2018-01-02', '11:21:49', 'Ibbanwala', 'colombo', 6.918068272649191, 79.85931172485357, 'post_image/3.jpg', 'High', 'active', 'Disaster', 1, 0, 0),
(32, '900870902v', 'Dewni Amarakoon', 'rsa', 'none', '1914 translation by H. Rackham', 'post_image/train-2134541.jpg', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum\r\n\r\n', '2018-01-02', '11:29:47', 'Paliyagoda', 'gampaha', 6.958113292735854, 79.92574467773443, 'post_image/apple-laptop-macbook-pro-notebook.jpg', 'High', 'active', 'Disaster', 3, 2, 2),
(34, '900870902v', 'Dewni Amarakoon', 'fi', 'none', 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has', 'post_image/career-firefighter-relaxing-job-162540.jpeg', 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum \r\n', '2018-01-02', '12:56:09', 'Malabe', 'gampaha', 6.904946398763843, 79.97071995849615, 'post_image/pexels-photo-64609.jpeg', 'High', 'active', 'Disaster', 1, 0, 2),
(35, '900870902v', 'Dewni Amarakoon', 'nd', 'ls', 'here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration ', 'post_image/pexels-photo-296878.jpeg', '\r\nhere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable\r\n', '2018-01-02', '11:36:04', 'Paliyagoda', 'colombo', 6.956750114056636, 79.92471470947271, 'post_image/pexels-photo-62348.jpeg', 'High', 'active', 'Disaster', 2, 2, 0),
(36, '900870902v', 'Dewni Amarakoon', 'nd', 'cy', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', 'post_image/pexels-photo-106344.jpeg', '\r\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.\r\n', '2018-01-02', '11:37:06', 'Kadawatha', 'gampaha', 7.000710628059877, 79.95080723876958, 'post_image/pexels-photo-262508.jpeg', 'High', 'active', 'Disaster', 2, 1, 3),
(37, '900870902v', 'Dewni Amarakoon', 'ebl', 'none', 'more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum', 'post_image/pexels-photo-356043.jpeg', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum\r\n', '2018-01-02', '11:38:35', 'Bandaragama', 'kaluthara', 6.714723914864788, 79.98857274169927, 'post_image/office-820390.jpg', 'High', 'active', 'Disaster', 2, 1, 7),
(38, '900870902v', 'Dewni Amarakoon', 'ebl', 'none', 'going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum ', 'post_image/career-firefighter-relaxing-job-162540.jpeg', 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum \r\n', '2018-01-02', '11:39:47', 'Habarakada', 'colombo', 6.866430747679767, 80.01329197998052, 'post_image/pexels-photo.jpg', 'High', 'active', 'Disaster', 2, 0, 0),
(39, '900870902v', 'Dewni Amarakoon', 'other', 'none', 'handful of model sentence structures, to generate Lorem Ipsum which looks reasonable', 'post_image/pexels-photo-351265.jpeg', 'here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable\r\n', '2018-01-02', '11:40:50', 'Nugegoda', 'colombo', 6.863703857533129, 79.90102543945318, 'post_image/sri-lanka-170864.jpg', 'High', 'active', 'Disaster', 2, 2, 3),
(40, '900870902v', 'Dewni Amarakoon', 'other', 'none', 'over the years, sometimes by accident, sometimes on purpose (injected humour and the like', 'post_image/henna-691901.jpg', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like', '2018-01-02', '11:42:27', 'Moratuwa', 'kaluthara', 6.7873446131590915, 79.89312901611333, 'post_image/pexels-photo-68912.jpeg', 'High', 'active', 'Disaster', 5, 0, 0),
(41, '900870903v', 'Dulitha Lanshan', 'nd', 'dr', 'simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old', 'post_image/sri-lanka-170864.jpg', 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum ', '2018-01-02', '12:22:26', 'Waththala', 'gampaha', 7.002073678705587, 79.91098179931646, 'post_image/construction-site-build-construction-work-159306.jpeg', 'Middle', 'active', 'Disaster', 3, 1, 3),
(42, '900870904v', 'Yasiru Perera', 'rsa', 'none', 'All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as ', 'post_image/pexels-photo-381949.jpeg', 'here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable\r\n', '2018-01-02', '12:24:42', 'Ballapitiya', 'kaluthara', 6.695970326095767, 80.07028355712896, 'post_image/manor-house-2359884.jpg', 'Middle', 'active', 'Disaster', 3, 1, 4),
(43, '900870905v', 'Thilanka Perera', 'fi', 'none', ' ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora', 'post_image/pexels-photo-518244.jpeg', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.\r\n', '2018-01-02', '12:26:13', 'Ragama', 'gampaha', 7.044326269552404, 79.91578831787115, 'post_image/construction-site-build-construction-work-159306.jpeg', 'Middle', 'active', 'Disaster', 0, 0, 0),
(44, '900870906v', 'Sahiru Gunawardana', 'ebl', 'none', 'The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using', 'post_image/man-people-space-desk.jpg', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like\r\n', '2018-01-02', '12:28:07', 'J-Ela', 'gampaha', 7.073628226136204, 79.91372838134771, 'post_image/pexels-photo-351265.jpeg', 'High', 'active', 'Disaster', 3, 0, 2),
(45, '900870906v', 'Sahiru Gunawardana', 'nd', 'ls', 'All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Intern', 'post_image/pexels-photo-297755.jpeg', 'here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable\r\n\r\n\r\n', '2018-01-02', '12:32:21', 'Wadduwa', 'gampaha', 6.634589916424299, 79.95286717529302, 'post_image/computer-472016.jpg', 'Low', 'active', 'Disaster', 0, 5, 0),
(46, '900870903v', 'Dulitha Lanshan', 'nd', 'ls', 'making it look like readable English. Many desktop publishing packages and web page ', 'post_image/pexels-photo-67112.jpeg', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like', '2018-01-02', '12:36:05', 'Yakkala', 'gampaha', 7.0862343102363905, 80.03183140869146, 'post_image/pexels-photo-114907.jpeg', 'High', 'active', 'alert', 0, 0, 0),
(47, '900870904v', 'Yasiru Perera', 'fi', 'none', ' All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the ', 'post_image/pexels-photo-356043.jpeg', '\r\nhere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable', '2018-01-02', '12:37:36', 'Artigala', 'colombo', 6.894039629195363, 80.05517735595708, 'post_image/pexels-photo-518244.jpeg', 'Middle', 'active', 'alert', 0, 0, 0),
(48, '900870902v', 'Dewni Amarakoon', 'ebl', 'none', 'Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one ', 'post_image/pexels-photo-288477.jpeg', 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum \r\n', '2018-01-02', '12:39:48', 'Naboda', 'kaluthara', 6.59230118011621, 80.09397282714849, 'post_image/', 'Middle', 'active', 'alert', 0, 0, 0),
(49, '900870905v', 'Thilanka Perera', 'nd', 'fl', 'It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate', 'post_image/sri-lanka-2455695_1920.jpg', 'here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable\r\n', '2018-01-02', '12:42:32', 'Wallampitiya', 'colombo', 6.943118109733095, 79.90480198974615, 'post_image/', 'Middle', 'active', 'alert', 0, 0, 0),
(50, '900870906v', 'Sahiru Gunawardana', 'ebl', 'none', 'Contabgiy kiulljh fsfsgdsg', 'post_image/railway-190929_1920.jpg', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum', '2018-01-02', '12:44:11', 'Thalawathugooda', 'colombo', 6.876315593409713, 79.94016423339849, 'post_image/', 'Low', 'active', 'alert', 0, 0, 0),
(51, '900870902v', 'Dewni Amarakoon', 'nd', 'fl', 'distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a', 'post_image/pexels-photo-244132.jpeg', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like', '2018-01-02', '01:02:15', 'Kaduwela', 'colombo', 6.933575471648641, 79.98170628662115, 'post_image/pexels-photo-67112.jpeg', 'High', 'active', 'Disaster', 2, 4, 0),
(52, '900870903v', 'Dulitha Lanshan', 'nd', 'cy', ' going through the cites of the word in classical literature, discovered the undoubtable source', 'post_image/ancient-192801_1920.jpg', '\r\nContrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum \r\n', '2018-01-02', '01:03:41', 'Batuwita', 'gampaha', 6.7477966636152535, 80.03904118652349, 'post_image/', 'High', 'active', 'Disaster', 0, 9, 3),
(53, '900870904v', 'Yasiru Perera', 'nd', 'dr', ' Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.', 'post_image/pexels-photo-518244.jpeg', 'here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable\r\n', '2018-01-02', '01:05:20', 'Wallampitiya', 'colombo', 6.941754887564332, 79.90548863525396, 'post_image/people-woman-coffee-meeting.jpg', 'High', 'active', 'Disaster', 8, 0, 0),
(54, '900870905v', 'Thilanka Perera', 'nd', 'ls', 'looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum', 'post_image/pexels-photo-140945.jpeg', 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum ', '2018-01-02', '01:07:51', 'Waboda', 'gampaha', 7.024904184380086, 79.99063267822271, 'post_image/macbook-laptop-ipad-apple-38519.jpeg', 'High', 'active', 'Disaster', 0, 8, 0),
(55, '900870906v', 'Sahiru Gunawardana', 'fi', 'none', 'predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200', 'post_image/pexels-photo-381949.jpeg', 'here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable\r\n', '2018-01-02', '01:09:42', 'Maradana', 'gampaha', 6.92232854293713, 79.86609234924322, 'post_image/pexels-photo.jpg', 'High', 'active', 'alert', 0, 0, 0),
(56, '900870902v', 'Dewni Amarakoon', 'nd', 'cy', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', 'post_image/pexels-photo-106344.jpeg', '\r\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.\r\n', '2018-01-02', '11:12:06', 'Kadawatha', 'gampaha', 7.000710628059877, 79.95080723876958, 'post_image/pexels-photo-262508.jpeg', 'High', 'active', 'Disaster', 2, 1, 3),
(57, '900870903v', 'Dulitha Lanshan', 'nd', 'dr', 'simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old', 'post_image/sri-lanka-170864.jpg', 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum ', '2018-01-02', '12:22:26', 'Waththala', 'gampaha', 7.002073678705587, 79.91098179931646, 'post_image/construction-site-build-construction-work-159306.jpeg', 'Middle', 'active', 'Disaster', 3, 1, 3),
(58, '900870905v', 'Thilanka Perera', 'nd', 'fl', 'It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate', 'post_image/sri-lanka-2455695_1920.jpg', 'here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable\r\n', '2018-01-02', '12:42:32', 'Wallampitiya', 'colombo', 6.943118109733095, 79.90480198974615, 'post_image/', 'Middle', 'active', 'alert', 0, 0, 0),
(59, '900870902v', 'Dewni Amarakoon', 'nd', 'fl', 'distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a', 'post_image/pexels-photo-244132.jpeg', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like', '2018-01-02', '01:02:15', 'Kaduwela', 'colombo', 6.933575471648641, 79.98170628662115, 'post_image/pexels-photo-67112.jpeg', 'High', 'active', 'Disaster', 2, 4, 0),
(60, '900870903v', 'Dulitha Lanshan', 'nd', 'cy', ' going through the cites of the word in classical literature, discovered the undoubtable source', 'post_image/ancient-192801_1920.jpg', '\r\nContrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum \r\n', '2018-01-02', '01:03:41', 'Batuwita', 'gampaha', 6.7477966636152535, 80.03904118652349, 'post_image/', 'High', 'active', 'Disaster', 0, 9, 3),
(61, '900870904v', 'Yasiru Perera', 'nd', 'dr', ' Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.', 'post_image/pexels-photo-518244.jpeg', 'here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable\r\n', '2018-01-02', '01:05:20', 'Wallampitiya', 'colombo', 6.941754887564332, 79.90548863525396, 'post_image/people-woman-coffee-meeting.jpg', 'High', 'active', 'Disaster', 8, 0, 0),
(62, '900870902v', 'Dewni Amarakoon', 'other', 'none', 'Event 01 from a Lorem Ipsum passage, and going through', 'post_image/pexels-photo-106344.jpeg', 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum ', '2018-01-02', '01:14:04', 'Pannipitiya', 'colombo', 6.841547296516718, 79.95458378906255, 'post_image/', 'High', 'active', 'event', 0, 0, 0),
(63, '900870903v', 'Dulitha Lanshan', 'other', 'none', 'Event 02 a handful of model sentence structures', 'post_image/construction-site-build-construction-work-159306.jpeg', 'here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable\r\n', '2018-01-02', '01:15:08', 'Gonapola', 'kaluthara', 6.755979263630189, 80.0177551757813, 'post_image/', 'High', 'active', 'event', 0, 0, 0),
(64, '900870904v', 'Yasiru Perera', 'nd', 'none', 'Event 03 from a Lorem Ipsum passage, and ', 'post_image/pexels-photo-109371.jpeg', 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum ', '2018-01-02', '01:16:05', 'Eldeniya', 'kaluthara', 7.0105926549788355, 79.97140660400396, 'post_image/', 'High', 'active', 'event', 0, 0, 0),
(65, '900870905v', 'Thilanka Perera', 'other', 'none', 'Event 04 dolor sit amet, consectetur, adipisci velit', 'post_image/pexels-photo-67112.jpeg', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.', '2018-01-02', '01:17:26', 'Habarakada', 'colombo', 6.86847590503422, 80.0064255249024, 'post_image/', 'High', 'active', 'event', 0, 0, 0),
(66, '900870906v', 'Sahiru Gunawardana', 'other', 'none', 'Event 05  and more recently with desktop ', 'post_image/pexels-photo-262508.jpeg', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum\r\n', '2018-01-02', '01:18:43', 'Abathale', 'colombo', 6.940817670032531, 79.94012131805425, 'post_image/', 'High', 'active', 'event', 0, 0, 0),
(67, '900870902v', 'Dewni Amarakoon', 'ebl', 'none', 'Boy Killed on Farm In Sri Lanka by Electrical Wire', 'post_image/4.jpg', 'WELIMADA, SRI LANKA â€“ A farmer was taken into custody after a 12-year-old boy was killed when he tread onto to an exposed current wire that had been placed to discourage animals from attacking the crops, police said today.â€It is illegal to place such electricity in an open area, and the suspect in this case has been very careless which eventually grabbed a lifeâ€, one senior policeman said.', '2018-01-02', '01:31:47', 'Paliyagoda', 'colombo', 6.956750114056636, 79.92608800048833, 'post_image/', 'High', 'active', 'Disaster', 1, 2, 0),
(68, '900870903v', 'Dulitha Lanshan', 'rsa', 'none', 'Waththala locals attack lorry driver over death of woman ', 'post_image/65.jpg', 'A tense situation arose as locals in the Wedamulla, Kothmale area were outraged by an accident that took the life of a woman who was run over by a lorry.\r\nAngered locals attacked the lorry and its driver following the accident, which occurred while the victim was crossing the road. The driver of the lorry has been arrested.\r\nThe News 1st correspondent in the area captured images of the immediate aftermath of the accident.\r\n', '2018-01-02', '01:37:38', 'Waththala', 'gampaha', 7.001732916417496, 79.91235509033208, 'post_image/23.jpg', 'High', 'active', 'Disaster', 1, 4, 0),
(69, '900870904v', 'Yasiru Perera', 'ebl', 'none', 'Multiple Electrocutions Reported After Flooding', 'post_image/234.jpg', 'Recent flooding throughout the world has lead to many electrical accidents and deaths.  Most happen with downed power lines in water or when people are standing in water and touch a faulty electrical wire at home.  If you experience flooding, please keep electrical safety in mind and dont go near downed power lines or try to activate or touch any electrical appliance while standing in water.\r\nBelow is a recent example among many of electrocution related to flooding.\r\nBatticaloa, Tamil, Sri Lanka â€“ 14 people have died so far in the floods in Batticaloa district according to Batticaloa District Secretariat. At least 10 persons have been reported missing in the district and 4 fishermen are missing in Ampaarai district. On Tuesday, a 17-year-old boy was electrocuted and a 19-year-old boy was seriously injured along Koayil Road in Onthaachchi-madam in Kaluvaagnchik-kudi division in Batticaloa district when they touched a live electric wire lying on the ground after strong winds.\r\n', '2018-01-02', '01:43:11', 'Colombo', 'colombo', 6.923351002084404, 79.8636032592774, 'post_image/', 'High', 'active', 'event', 0, 0, 0),
(70, '900870905v', 'Thilanka Perera', 'nd', 'fl', '2017 Sri Lanka floods Kaduwela', 'post_image/456.jpg', 'The 2017 Sri Lanka floods resulted from a heavy southwest monsoon, beginning around 18 to 19 May 2017.Flooding was worsened by the arrival of the precursor system to Cyclone Mora, causing flooding and landslides throughout Sri Lanka during the final week of May 2017 The floods affected 15 districts, killed at least 208 people and left a further 78 people missing. As of 3 June, 698,289 people were affected, while 11,056 houses were partially damaged and another 2,093 houses completely destroyed. According to Al Jazeera, about 600,000 people have been displaced due to the floods.\r\n', '2018-01-02', '01:46:37', 'Kaduwela', 'colombo', 6.925055095739571, 79.93261113281255, 'post_image/', 'High', 'active', 'Disaster', 35, 5, 14),
(71, '900870906v', 'Sahiru Gunawardana', 'fi', 'none', 'Sixteen injured in Malabe  area', 'post_image/67.jpg', 'Meanwhile, a motor accident took place in the Palampatar area on the Kantale â€“ Trincomalee area around 7 on Saturday night.\r\nThe accident occurred when a tractor transporting a harvesting machine from Trincomalee to Kantale collided with an on oncoming mini-lorry.\r\nSixteen people travelling in the mini-lorry were admitted to the Trincomalee Base Hospital with injuries.\r\n', '2018-01-02', '01:49:10', 'Malabe', 'colombo', 6.914148790037257, 79.97106328125005, 'post_image/', 'High', 'active', 'Disaster', 7, 2, 0),
(72, '900870902v', 'Dewni Amarakoon', 'nd', 'fl', 'Floods and landslides in Sri Lanka kill at least 150 people ', 'post_image/678.jpg', 'Landslides and floods in Sri Lanka have killed at least 151 people and the country faces the risk of more mudslides as torrential rains continue.\r\nMore than 100 people are still missing after the worst rains in the Indian Ocean island since 2003. The state-run National Building Research Organization warned people in seven out of the countryâ€™s 25 districts on Sunday to evacuate from unstable slopes if rains continued for the next 24 hours.\r\nThe meteorology department of Meteorology said there could be heavy rainfalls of above 100 millimetres in central Sri Lanka within the next 36 hours.\r\nThe death toll has risen to 151, while 111 people are still reported missing and 95 injured, according to the state-run Disaster Management Center. Nearly 500,000 people have been affected by the disaster, the worst since the 2004 Boxing Day tsunami, and the downpours have displaced more than 100,000.\r\n', '2018-01-02', '02:12:59', 'Wallampitiya', 'colombo', 6.942436499142387, 79.90583195800787, 'post_image/88765.jpg', 'High', 'active', 'Disaster', 150, 20, 55),
(73, '900870903v', 'Dulitha Lanshan', 'rsa', 'none', 'Accsident Southern Way', 'post_image/2332.jpg', 'A van that veered off near the 23 kilometres [R] point in the Kaluthara North Police Division, along the Southern Expressway and collided on the safety railings has left one dead and nine  injured.\r\nAccording to the police, the injured persons are currently receiving treatment at the Nagoda Hospital in Kalutara.\r\nThey were identified as residents of Gampola. The cause of the accident is yet to be ascertained. Police added that the van was carrying passengers returning from a religious event held in Matara.\r\n', '2018-01-02', '02:15:13', 'Rekka Waththa', 'gampaha', 6.735522504392123, 79.99861493225103, 'post_image/3.jpg', 'High', 'active', 'Disaster', 1, 4, 0),
(74, '900870904v', 'Yasiru Perera', 'fi', 'none', 'Fire destroys building in Nugegoda', 'post_image/eef.jpg', 'A fire has broken out in a building located at Nicholas Marcus Fernando Street in front of the Nugegoda Bus Stop on Friday night.\r\nThe Fire Brigade of the Nugegoda Municipal Council said they managed to douse the fire by morning. It is reported that the fire has caused serious damage to the second, third and fourth floors of the building.\r\nPolice said that computer and tuition classes have been conducted in these floors and it is suspected that the fire has broken out due to a power leak.\r\nThe Nugegoda Police has launched investigations into the incident.\r\n', '2018-01-02', '02:47:12', 'Nugegoda', 'colombo', 6.865749026608002, 79.89896550292974, 'post_image/455.jpg', 'High', 'active', 'Disaster', 4, 2, 2),
(75, '900870905v', 'Thilanka Perera', 'rsa', 'none', 'Motorcyclist dies in Bandaragama vehicle collision', 'post_image/23.jpg', 'A motorcyclist has been killed after his vehicle collided with a bus in Midheewatte, Kekirawa.\r\nThe victim has been identified as 40-year-old resident of Maradhan-Kadawala.\r\nThe driver of the bus has been arrested by the police.\r\nMeanwhile, in a separate incident, an individual who was hit by a bus at the Ratnapura bus halt has succumbed to his injuries.\r\nThe victim was a 63-year-old resident of Nivithigala.\r\n', '2018-01-02', '02:48:53', 'Bandaragama', 'kaluthara', 6.713019072990428, 79.98582615966802, 'post_image/34.jpg', 'High', 'active', 'Disaster', 2, 1, 0),
(79, '900870905v', 'Thilanka Perera', 'fi', 'none', 'Fire crackers spark several fires in Sri Lanka', 'post_image/123.jpg', 'A fire caused by fire crackers has been reported in a few areas in the country.\r\nA fire broke out early this morning in a polythene warehouse along the Attidiya road in Bellanthota, Dehiwala. The Fire Fighting Unit of Dehiwala said that five fire engines and 10 firemen were deployed to extinguish the fire. The cause for the fire is yet to be ascertained. However,  it is suspected that fire was caused due to fireworks.\r\nMeanwhile, a fire was also reported at a 10-storey building in Vander Place, Dehiwala earlier this morning. Eight storeys of the building have been damaged. However, no damage to other property has been reported.\r\n', '2018-01-02', '08:48:51', 'Kottawa', 'colombo', 6.82143506636489, 79.93398442382818, 'post_image/67.jpg', 'High', 'active', 'Disaster', 5, 2, 3),
(80, '900870906v', 'Sahiru Gunawardana', 'fi', 'none', 'Fire ravages fishing trawler and vessels in Tangalle', 'post_image/455.jpg', 'A fire broke out on a multi-day fishing trawler which was anchored at the Kudawella Fisheries Harbour in Tangalle on Monday afternoon.\r\nThe police say that another five vessels located adjacent to the trawler were also destroyed in the fire.\r\nThe fire had broken out on the trawler at about 2 p.m. Monday at the Kudawella Fisheries Harbour in Tangalle.\r\nThe fire had spread when fishermen attempted to take the vessel out of the harbour in order to put out the fire.', '2018-01-02', '08:50:50', 'Mathugama', 'kaluthara', 6.5442104125286855, 80.10701909179693, 'post_image/', 'High', 'active', 'Disaster', 3, 2, 0),
(81, '900870903v', 'Dulitha Lanshan', 'rsa', 'none', 'Three killedin van-bus collision', 'post_image/3.jpg', 'A motor accident took place on the Avissawella â€“ Nittambuwa Main road around 7 on Saturday night as a result of a collision between a private bus and a van in the Erundeniya area in Amithirigala.\r\nThree people were killed in the accident. Police said that nine people were travelling the van at the time.\r\n', '2018-01-02', '08:52:44', 'Awissawella', 'colombo', 6.954705338617924, 80.16126408691412, 'post_image/', 'High', 'active', 'Disaster', 3, 4, 0),
(83, '900870904v', 'Yasiru Perera', 'rsa', 'none', 'Motor accident claims life of expectant mother', 'post_image/34.jpg', 'A motor accident which took place in the Athdalapitiya area in Bandarawela this morning claimed the life of an expectant mother.\r\nPolice said the woman had returned home from the market with her son in the car when the vehicle fell off a 150 metre precipice while she was trying to park it.\r\nâ€œWe were down here when we heard a noise. When I came the vehicle had fallen and was covered by the trees. There was no one around. I called the people around and got her out of the vehicleâ€, said a witness.\r\nThe injured child was admitted to the Bandarawela District Hospital.\r\n', '2018-01-02', '09:27:35', 'Jayawardhanapura', 'colombo', 6.887563615963445, 79.90686192626958, 'post_image/', '', 'new', 'Disaster', 3, 2, 0),
(84, '900870906v', 'Sahiru Gunawardana', 'fi', 'none', 'Fire erupts at Mattegoda rubber factory', 'post_image/67.jpg', 'A fire has broken out at a rubber processing factory in Mattegoda. The Police Media Unit notes that the fire which erupted on Saturday morning has completely burnt down the factory.\r\nThey added that the fire was doused by the Fire and Rescue Unit of the Dehiwala â€“ Mount Lavinia Municipal Council. Police said that they have commenced investigations along with the Piliyandala electrical engineers office.\r\n', '2018-01-02', '09:29:55', 'Waliwita', 'gampaha', 6.93715398359421, 79.95818867797857, 'post_image/', '', 'new', 'Disaster', 2, 6, 2);

-- --------------------------------------------------------

--
-- Table structure for table `post_comment`
--

CREATE TABLE `post_comment` (
  `comment_id` int(11) NOT NULL,
  `postid` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `comment` varchar(500) NOT NULL,
  `date` date NOT NULL,
  `time` time NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `post_comment`
--

INSERT INTO `post_comment` (`comment_id`, `postid`, `name`, `comment`, `date`, `time`) VALUES
(7, 74, 'Lasitha Gayashan', 'Where Is This ? ', '2018-01-02', '03:06:15'),
(8, 74, 'Thilanka Perera', 'This IS Nugegoda', '2018-01-02', '03:06:40'),
(9, 74, 'Jagath', 'I Saw This .', '2018-01-02', '03:07:18'),
(10, 75, 'Lasiiii', 'goood', '2018-01-09', '07:03:31');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `nic` varchar(10) NOT NULL,
  `name` varchar(255) NOT NULL,
  `profile_pic` varchar(255) NOT NULL,
  `job` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `user_type` varchar(10) NOT NULL,
  `address` varchar(255) NOT NULL,
  `age` int(2) NOT NULL,
  `contact_number` int(12) NOT NULL,
  `user_status` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`nic`, `name`, `profile_pic`, `job`, `password`, `email`, `user_type`, `address`, `age`, `contact_number`, `user_status`) VALUES
('900870900v', 'Deshan Freanando', 'profileimages/ethan-hoover-311143.jpg', 'Derector', 'nsbm@1234', 'deshan@gmail.com', 'admin', '123/D,Malabe.', 23, 712233556, 'active'),
('900870901v', 'Lasitha Gayashan', 'profileimages/jeslyn-chanchaleune-349125.jpg', 'Manager', 'nsbm@1234', 'lasitha@gmail.com', 'manager', '136/D,Gatahaththa,Eheliyagoda', 22, 711133448, 'active'),
('900870902v', 'Dewni Amarakoon', 'profileimages/allef-vinicius-152932.jpg', 'Gramasewaka', 'nsbm@1234', 'dewni@gmail.com', 'user', 'Kothwila Road,Eheliyagoda', 21, 718866117, 'active'),
('900870903v', 'Dulitha Lanshan', 'profileimages/222.jpeg', 'Policeman', 'nsbm@1234', 'dulitha@gmail.com', 'user', 'Moragahahena,Horana', 27, 765588994, 'active'),
('900870904v', 'Yasiru Perera', 'profileimages/pic11.jpeg', 'Postman', 'nsbm@1234', 'yasiru@gmail.com', 'user', 'Minuwangoda,Kadawatha', 26, 725566998, 'active'),
('900870905v', 'Thilanka Perera', 'profileimages/111.jpg', 'Policeman', 'nsbm@1234', 'thilanka@gmail.com', 'user', 'Miriswaththa,Panadura', 29, 756984214, 'active'),
('900870906v', 'Sahiru Gunawardana', 'profileimages/Member-of-Team.jpeg', 'Gramasewaka', 'nsbm@1234', 'sahiru@gmail.com', 'user', '165/G,Nugegoda', 34, 715566699, 'active'),
('900870907v', 'Sudara Ranmal', 'profileimages/pic1.jpg', 'Policeman', 'nsbm@1234', 'sudara@gmail.com', 'user', '45/B,Wennappuwa.', 43, 715566998, 'inactive'),
('976651545v', 'Geethika Sewwandi', 'profileimages/IMG_4737.JPG', 'Policeman', 'nsbm@123', 'geethika@gmail.com', 'user', 'Sethsiri stores,Pohrabawa', 22, 711662213, 'active');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `post`
--
ALTER TABLE `post`
  ADD PRIMARY KEY (`postid`);

--
-- Indexes for table `post_comment`
--
ALTER TABLE `post_comment`
  ADD PRIMARY KEY (`comment_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`nic`) USING BTREE;

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `post`
--
ALTER TABLE `post`
  MODIFY `postid` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=87;
--
-- AUTO_INCREMENT for table `post_comment`
--
ALTER TABLE `post_comment`
  MODIFY `comment_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
